### ISSUE TITLE
Request for Docs

### ISSUE THREAD

**Issue by ddanon** [farukalpay/SMS-Sender#3]
- [ ] What exactly should `numbers.txt` look like?
- [ ] Please provide an example `numbers.txt` file that one could start with

**Comment by farukalpay** [comment]
The `number.txt` represents the list of numbers that I use, which are fetched from a txt file. If the file path is in the same directory as the project, you can directly specify the path to the txt file without writing the full path. Otherwise, you may need to specify the file path in the form of C:\..\.. Below, you can find the function that indicates how phone numbers are validated.

```
def is_valid_number(number, country_code):
    if country_code == "TR":
        pattern = r'^\d{10}$'
    else:
        pattern = r'^\d{7,11}$'
    return (re.match(pattern, number))`
```

This regular expression pattern `'^\d{7,11}$'` represents a string of only digits that is at least 7 digits long but no more than 11 digits long. 

Here is an example numbers.txt

```
Hello World!
3456789098 10
1234567890 3
3456789086
```

Here, even though the numbers are not entered in a regular manner, the function will only take the valid numbers from this list. Here is the function

```
def read_file(file_path):
    if not file_path or not os.path.isfile(file_path):
        print(f"{Fore.RED}Invalid file path. Please try again.{Fore.RESET}")
        return []
    encoding = get_encoding(file_path)
    with open(file_path, 'r', encoding=encoding) as f:
        items = [line.strip().split()[0] for line in f.readlines() if line.strip()]
    items = list(set(items))  # Remove duplicates
    return items
```

This function first checks the validity of the file path, then determines the encoding format of the file using the chardet library, and opens the file with that encoding format.

`[line.strip().split()[0] for line in f.readlines() if line.strip()]`

This part of code reads the specified file and fetches items (for instance, phone number or proxylist) from the first column of each line in the file.

Finally, this function takes a list of phone numbers as an input. For each number, it uses the function is_valid_number that i mentioned in the beginning. Based on the results, it assigns the valid phone numbers to a variable named **valid_numbers**, while the invalid numbers are assigned to a variable named **invalid_numbers**.

If you have any more questions, feel free to ask. Additionally, I will soon create a documentation that explains all functions in detail.
